### ISSUE TITLE
Wrong version (0.1.2) in "kompose versione" (instead of 0.2.0)

### ISSUE THREAD

**Issue by pivulic** [kubernetes-incubator/kompose#411]
## Problem
I'm having the same issue as http://stackoverflow.com/questions/41738374/kubernestes-persistentvolumeclaim-is-not-bound, but thought I should upgrade from 0.1.2 to 0.2.0. 

However, running `kompose version` displays **0.1.2 (HEAD)** instead of **0.2.0**

## How To Recreate
Following the Mac OS steps:
```curl -L https://github.com/kubernetes-incubator/kompose/releases/download/v0.2.0/kompose-darwin-amd64 -o kompose
chmod +x kompose
sudo mv ./kompose /usr/local/bin/kompose
kompose version
```

Same result if I run:
```
cd /usr/local/bin/
./kompose version
```
## Actual Result
`0.1.2 (HEAD)`

## Expected Result
`0.2.0`

**Comment by surajnarwade** [comment]
this issue has  already been fixed.

$ kompose version
0.2.0 (64433fd)

**Comment by cdrage** [comment]
@surajnarwade @pivulic 

Looks like I created the binaries incorrectly (did not sync with master before release, boo on me!).

I'll update them so it *actually* shows 0.2.0 as the expected result on `kompose version`.

In regards to volumes, @surajnarwade is correct that you need to create a Persistent Volume before using PersistentVolumeClaim.

**Comment by cdrage** [comment]
@pivulic Release has been updated to include the proper `kompose version` output.

Mind checking it again? :)

**Comment by cdrage** [comment]
Going to close this for now as I was able to confirm that the version works with the new binary!

**Comment by pivulic** [comment]
Thanks @cdrage! (and sorry for the late reply) Works perfectly! 👍 

Regarding creating a Persistent Volume, I looked through the [guide](https://kubernetes.io/docs/user-guide/persistent-volumes/), but isn't `kompose up` supposed to take care of it, if my `docker-compose.yml` file already has the volumes configured? 

Let me know if I should create a separate issue for this, or if you can refer me somewhere else :)

**Comment by surajssd** [comment]
@pivulic it might feel like kompose should take care of this but the problem here is that `PV` can only be created by user with `system:admin` privileges, and there are multiple ways to create PV with various backends, now kompose might not know beforehand what is the type of cluster(minikube where hostPath can be used, multi-node cluster with admin access, cluster with only nfs, openshift online, etc.) a user is gonna deploy application on. So a generated PV might not always work, with different clusters. 

Kompose tries to generate configs which are cluster neutral, I mean they will work on any cluster. But generating configs which need cluster info can be little hard to do.

But in case anyone has better way of doing that it would be awesome, I cannot think of any as of now.

**Comment by cdrage** [comment]
Yeah, we're going to improve how we convert volumes in terms of logging as well as documentation, it's the biggest thorn when converting at the moment as they don't exactly translate 1-1 with Kubernetes.
