### ISSUE TITLE
Deprecating v1 and only supporting v2 and v3

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#430]
v1 will eventually be deprecated by docker-compose. As well as the fact that v1 honestly doesn't convert that well when going from Docker to Kubernetes (especially with the networking + volumes section of v2 providing a lot of ease for it).

Should we deprecate v1 and focus our efforts on only v2 and v3?

**Comment by kadel** [comment]
This made me thinking, so I tried to get some statistics how are different versions used.

docker-compose.yml files in github, only ~29% v2 files  and rest v1


How I got there:
I've used Google BigQuery with github public data set: https://cloud.google.com/bigquery/public-data/github

To make it easy I assume that there is no v3 (or at least right now it is so small number that it doesn't matter).
Another assumption is that v2 files are all the docker-compose.yml files that contains "version:" string. This gets a few false positives but I shouldn't be statistically significant.


I've used sample tables, they are smaller, but statistically it shouldn't matter.

all docker-compose.yml files: 197
files with "version:": 57 ~= 29%

queries I've used:
```sql
SELECT
  COUNT(*)
FROM
  [bigquery-public-data:github_repos.sample_contents]
WHERE
  sample_path LIKE "%docker-compose.y%"
```

```sql
SELECT
  COUNT(*)
FROM
  [bigquery-public-data:github_repos.sample_contents]
WHERE
  sample_path LIKE "%docker-compose.y%"
  AND content CONTAINS "version:"
```

And now when I've done all this I'm not sure if it says anything :rofl: 
Reason behind big number of old v1 files might be that they are just old and nobody is using them :-D
It might be better to get only files that were modified in last year or so, but that will be tricky to do :-(

I'll keep it here, because someone might find it interesting. 

**+1 for deprecating v1 in kompose.**

**Comment by sebgoa** [comment]
nice data query. I think it is very informative.
we could try to run a poll on Twitter (not that it would be super viable but it would give some data points).

I think we need to have v3 supported (in a branch), before removing v1.

We can have a policy to support the current version of compose and the one before.

**Comment by kadel** [comment]
Agreed we shouldn't drop v1 before supporting v3

**Comment by cdrage** [comment]
I agree with @kadel 

Let's stick with v2 / v3 for now  and still support v1 (it's not that hard to maintain)
